### ISSUE TITLE
Change entry in the list

### ISSUE THREAD

**Issue by heribertmsb** [bramwaas/joomla_mod_simple_ical_block#21]
This is a great tool. Hoever I would like to ommit the starting time in the summary line.
Leaving empty "Time format time summary line" doe noct work
Hoe to modify the code?

**Comment by bramwaas** [comment]
Hi,

Thank you for reporting this issue.
Emptying the field should work, only Joomla fills empty fields with the default.
Enter in that case: <> 
(that is, only less than character followed by greater than character). 
That will do the trick.

Regards Bram.

**Comment by heribertmsb** [comment]
Thank's this works.

**Comment by heribertmsb** [comment]
Case closed
