### ISSUE TITLE
Joomla\CMS\Form\Form::validateField() rule `cleartransientnow` missing.

### ISSUE THREAD

**Issue by ChristianAlmgren** [bramwaas/joomla_mod_simple_ical_block#23]
trying to save a calendar ID, I get this error
Joomla\CMS\Form\Form::validateField() rule `cleartransientnow` missing.

**Comment by bramwaas** [comment]
Hi,

Thanks for reporting this issue.
I will look at it and hope to solve it this weekend.

Regards

Bram Waasdorp

**Comment by bramwaas** [comment]
The error you report is the same as in issue #10 .
If you are using Joomla 3 unfortunately the answer will be the same too.
The module is not supported in older versions than Joomla 4.
